### PR TITLE
Depend on db.ncbitaxonomy

### PR DESCRIPTION
**Pull request by agarciamontoro**
When ready, for tests.

### CODE REVIEW

**Comment by agarciamontoro** [comment]
Pretty straightworfard code here: now, tests depend on files `ohnosequences.db.ncbitaxonomy{names,nodes}`, that are downloaded if needed.

In a future PR we could isolate `fileUtils` stuff could on a new repo, as we are using it from several projects (so we are repeating code).

@eparejatobes review if you want.

**Comment by agarciamontoro** [comment]
Gñeh, Travis is trying to download the files from S3 but:

```
Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
```

**Comment by eparejatobes** [comment]
Make tests downloading data ReleaseOnly

**Comment by agarciamontoro** [comment]
Mr. Travis is now happy.

**Pull request merged**
